/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-08-16 18:51:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=BIG5");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Lotto649</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.min.js\" integrity=\"sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("*{\r\n");
      out.write("font-family: \"微軟正黑體\";\r\n");
      out.write("font-size: 24px;\r\n");
      out.write("}\r\n");
      out.write(".wrapper{\r\n");
      out.write("width: 600px;\r\n");
      out.write("\r\n");
      out.write("border: 5px solid #ff2244;\r\n");
      out.write("padding: 20px;\r\n");
      out.write("background: #eeeeee;\r\n");
      out.write("}\r\n");
      out.write("#wen{\r\n");
      out.write("color:#ff2244;\r\n");
      out.write("font-size: 36px;\r\n");
      out.write("user-select: none;\r\n");
      out.write("}\r\n");
      out.write("#wen:hover{\r\n");
      out.write("\tcolor: #ffaacc;\r\n");
      out.write("\ttransition: 0.5s;\r\n");
      out.write("}\r\n");
      out.write(".btn{\r\n");
      out.write("color:#ffc408;\r\n");
      out.write("font-size: 24px;\r\n");
      out.write("background: #2d3a3a;\r\n");
      out.write("margin: 5px;\r\n");
      out.write("}\r\n");
      out.write("#pred_btn,.predict_Go{\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tbackground: #aaeecc;\r\n");
      out.write("}\r\n");
      out.write("#pred_btn,.predict_Go:hover{\r\n");
      out.write("\tbackground: #2d3a3a;\r\n");
      out.write("\tcolor: #aaeecc;\r\n");
      out.write("}\r\n");
      out.write(".predict_Num{\r\n");
      out.write("\twidth: 210px;\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tline-height: 20px;\r\n");
      out.write("}\r\n");
      out.write(".ansText{\r\n");
      out.write("\tmargin: 10px 0;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\t/* background: #ffaacc; */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("\t<h1 id=\"wen\" onclick=\"javascript:window.location.reload()\" title=\"重新整理\">Hello World</h1>\r\n");
      out.write("\t<input class=\"btn\" value=\"官方網站\" type=\"button\" onclick=\"window.open('https://www.taiwanlottery.com.tw/lotto/lotto649/history.aspx','_blank')\" />\r\n");
      out.write("\t<a id=\"url_lotto\" href=\"https://www.taiwanlottery.com.tw/lotto649/index.asp\" target=\"_blank\">遊戲規則</a>\r\n");
      out.write("\r\n");
      out.write("\t<h2>準備好了嗎 ?</h2>\r\n");
      out.write("<button class=\"lucky\">提升幸運值</button>\r\n");
      out.write("<button id=\"pred_btn\">幸運轉蛋</button>\r\n");
      out.write("<p class=\"up\">祝您好運</p>\r\n");
      out.write("\r\n");
      out.write("\t<form id=\"formNum_main\" action=\"index.jsp\" method=\"post\">\r\n");
      out.write("\t    \t<select onchange=\"handler_form(this)\" name=\"n1\" class=\"selectNum1\"> </select>\r\n");
      out.write("\t    \t<select onchange=\"handler_form(this)\" name=\"n2\" class=\"selectNum2\"> </select>\r\n");
      out.write("\t    \t<select onchange=\"handler_form(this)\" name=\"n3\" class=\"selectNum3\"> </select>\r\n");
      out.write("\t    \t<select onchange=\"handler_form(this)\" name=\"n4\" class=\"selectNum4\"> </select>\r\n");
      out.write("\t    \t<select onchange=\"handler_form(this)\" name=\"n5\" class=\"selectNum5\"> </select>\r\n");
      out.write("\t\t\t<select onchange=\"handler_form(this)\" name=\"n6\" class=\"selectNum6\"> </select>\r\n");
      out.write("\t\t\t<br><br>\r\n");
      out.write("\t\t\t<!-- 開獎欄位 -->\r\n");
      out.write("\t\t\t<select onchange=\"handler_option(this)\" name=\"random_seed\" class=\"random_seed\"> </select>\r\n");
      out.write("\t\t\t<!-- 送出資料 -->\r\n");
      out.write("\t        <input class=\"btn\" id=\"submit_btn\" name=\"submit\" type=\"submit\" value=\"開獎\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<!-- 預測碼功能: 無限期維修中 -->\r\n");
      out.write("\t<button name=\"predict_Num\" class=\"predict_Num\">專屬預測號碼!</button>\r\n");
      out.write("\t<button name=\"predict_Go\" class=\"predict_Go\">確定</button>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"ansText\"></div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tlet wen = document.querySelector('#wen')\r\n");
      out.write("\tlet selectNum1 = document.querySelector('.selectNum1')\r\n");
      out.write("\tlet selectNum2 = document.querySelector('.selectNum2')\r\n");
      out.write("\tlet selectNum3 = document.querySelector('.selectNum3')\r\n");
      out.write("\tlet selectNum4 = document.querySelector('.selectNum4')\r\n");
      out.write("\tlet selectNum5 = document.querySelector('.selectNum5')\r\n");
      out.write("\tlet selectNum6 = document.querySelector('.selectNum6')\r\n");
      out.write("\r\n");
      out.write("\tlet random_seed = document.querySelector('.random_seed')\r\n");
      out.write("\tlet pred_btn = document.querySelector('#pred_btn')\r\n");
      out.write("\tlet formNum_main = document.querySelector('#formNum_main')\r\n");
      out.write("\tlet submit_btn = document.querySelector('#submit_btn')\r\n");
      out.write("\tlet ansText = document.querySelector('.ansText')\r\n");
      out.write("\t\r\n");
      out.write("\t// 預測碼功能(更新中) todo.. ======================================================\r\n");
      out.write("\t\r\n");
      out.write("\tlet lucky = document.querySelector('.lucky')\r\n");
      out.write("\tlet predict_Num = document.querySelector('.predict_Num')\r\n");
      out.write("\tlet predict_Go = document.querySelector('.predict_Go')\r\n");
      out.write("\tlet up = document.querySelector('.up')\r\n");
      out.write("\tlet count = 0\r\n");
      out.write("\t\r\n");
      out.write("\t// 取10期獎號作比對樣本\r\n");
      out.write("\tlet ans1 = [\"19\",\"45\",\"44\",\"09\",\"06\",\"40\",\"01\"]\r\n");
      out.write("\tlet ans2 = [\"31\",\"01\",\"11\",\"33\",\"05\",\"19\",\"06\"]\r\n");
      out.write("\tlet ans3 = [\"45\",\"19\",\"18\",\"16\",\"33\",\"17\",\"25\"]\r\n");
      out.write("\tlet ans4 = [\"35\",\"08\",\"23\",\"22\",\"29\",\"10\",\"02\"]\r\n");
      out.write("\tlet ans5 = [\"37\",\"21\",\"35\",\"20\",\"02\",\"24\",\"09\"]\r\n");
      out.write("\tlet ans6 = [\"25\",\"36\",\"03\",\"33\",\"16\",\"31\",\"14\"]\r\n");
      out.write("\tlet ans7 = [\"30\",\"25\",\"15\",\"05\",\"41\",\"06\",\"29\"]\r\n");
      out.write("\tlet ans8 = [\"49\",\"29\",\"32\",\"10\",\"04\",\"24\",\"43\"]\r\n");
      out.write("\tlet ans9 = [\"05\",\"04\",\"22\",\"49\",\"27\",\"46\",\"41\"]\r\n");
      out.write("\tlet ans10 = [\"46\",\"04\",\"44\",\"34\",\"22\",\"17\",\"13\"]\r\n");
      out.write("\tlet ansAll = [ans1,ans2,ans3,ans4,ans5,ans6,ans7,ans8,ans9,ans10]\r\n");
      out.write("\t\r\n");
      out.write("\t// 開獎號碼\r\n");
      out.write("\ts = Math.round(Math.random()*9)+1\r\n");
      out.write("\tansLotto = ansAll[s]\r\n");
      out.write("\tansLotto.pop()\r\n");
      out.write("\r\n");
      out.write("\t// 專屬預測號碼: 100%中獎\r\n");
      out.write("\tpredict_Num.onclick = function(){\r\n");
      out.write("\t\tcount += 1\r\n");
      out.write("\t\tthis.innerHTML=(this.innerHTML==\"戳我戳我!\"?\"戳壞了\":\"戳我戳我!\")\r\n");
      out.write("\t\tpredict_Go.style.display = \"none\"\r\n");
      out.write("\r\n");
      out.write("\t\tif(count%5==0){\r\n");
      out.write("\t\t\tpredict_Go.style.display = \"inline\"\r\n");
      out.write("\t\t\tar =  ansLotto\r\n");
      out.write("\t\t\tthis.innerHTML = ar\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t// 將預測號碼 設定為 開獎號碼\r\n");
      out.write("\tpredict_Go.onclick = function(){\r\n");
      out.write("\t\trandom_seed.innerHTML += '<option selected>'+ ar +'</option>'\r\n");
      out.write("\t\tarFun(ar)\r\n");
      out.write("\t\tpredict_Num.onclick()\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// =======================================================================\r\n");
      out.write("\r\n");
      out.write("\t// 開獎按鈕: 檢測重複號碼\r\n");
      out.write("\tsubmit_btn.onclick = function(){\r\n");
      out.write("\t\tc = [currentNum()] // 取得當前值(通用函式)\r\n");
      out.write("\t\tcheckNum = c.toString().split(',')\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tticket = true // 對獎門票\r\n");
      out.write("\t\tfor(i=0; i<6; i++){\r\n");
      out.write("\t\t\tfor(j=0; j<i; j++){\r\n");
      out.write("\t\t\t\tif(checkNum[i]==checkNum[j]){\r\n");
      out.write("\t\t\t\t\twen.innerHTML = \"號碼重複，請重新設定\"\r\n");
      out.write("\t\t\t\t\tansText.innerHTML += \"<br>\" + \"請檢查重複值 \" +\"<span style='color:#ff2244'>\"+ checkNum[i] +\"</span>\" + \"<br>\"\r\n");
      out.write("\t\t\t\t\tticket = false // 有重複值就沒收門票\r\n");
      out.write("\t\t\t\t\tbreak // 終止對獎\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif(ticket){ // 門票為 true 即符合對獎資格\r\n");
      out.write("\t\t\twen.innerHTML = \"經費不足，無限期請求金援\"\r\n");
      out.write("\t\t\tlottoAns(checkNum) // 呼叫對獎函式\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 對獎函式: \t\r\n");
      out.write("\tfunction lottoAns(checkNum){\r\n");
      out.write("\t\tansCurrent = ansAll[s] // 完整獎號\r\n");
      out.write("\t\tlet checkCount = 0\r\n");
      out.write("\t\tfor(i=0; i<7; i++){\r\n");
      out.write("\t\t\tfor(j=0; j<6; j++){\r\n");
      out.write("\t\t\t\tif(checkNum[j]==ansCurrent[i]){\r\n");
      out.write("\t\t\t\t\tcheckCount+=1\r\n");
      out.write("\t\t\t\t\tansText.innerHTML += checkNum[j] + \" 號碼符合! 目前累積 \" + checkCount + \" 個號碼獎號\" + \"<br>\"\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(checkCount>=3){\r\n");
      out.write("\t\t\tansText.innerHTML += \"恭喜中獎!本組[ \" + checkNum + \" ]獎號共符合\" + checkCount + \"個號碼\" + \"<br><br>\"\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tansText.innerHTML += \"可惜！沒有中獎，下去領500\" + \"<br>\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 取得當前值(通用函式)\r\n");
      out.write("\tfunction currentNum(){\r\n");
      out.write("\t\tlet lst = []\r\n");
      out.write("\t\tlst += formNum_main.n1.value +\",\"+ formNum_main.n2.value +\",\"+\r\n");
      out.write("\t\t\t\tformNum_main.n3.value +\",\"+ formNum_main.n4.value +\",\"+\r\n");
      out.write("\t\t\t\tformNum_main.n5.value +\",\"+ formNum_main.n6.value\r\n");
      out.write("\t\treturn lst\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 顯示按鈕(幸運轉蛋)\r\n");
      out.write("\tlucky.onclick = function(){\r\n");
      out.write("\t\tpred_btn.style.display = \"inline\"\r\n");
      out.write("\t\tlucky.style.display = \"none\"\r\n");
      out.write("\t\tup.innerHTML = \"發大財！\"\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 亂數不重複(通用函式)\r\n");
      out.write("\tlet ar = []\r\n");
      out.write("\tfunction roll(){\r\n");
      out.write("\t\tfor(i=0; i<6; i++){\r\n");
      out.write("\t\t\tlet k = Math.round(Math.random()*48)+1\r\n");
      out.write("\t\t\tif(k<10){ // 補0\r\n");
      out.write("\t\t\t\tk = \"0\"+k\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tar.push(k)\r\n");
      out.write("\t\t\tfor(j=0; j<i; j++){\r\n");
      out.write("\t\t\t\tif(ar[j]==k){\r\n");
      out.write("\t\t\t\t\ti--\r\n");
      out.write("\t\t\t\t\tar.pop()\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\troll() // 先取得一組亂數\r\n");
      out.write("\tconstructor() // 建構六組單選欄位\r\n");
      out.write("\trandom_seed.innerHTML += '<option selected>'+ ar +'</option>' // 第一次取得的亂數 當作預設號碼\r\n");
      out.write("\t\r\n");
      out.write("\t// 幸運轉蛋:亂數產生樂透號碼(不重複)\r\n");
      out.write("\tpred_btn.onclick = function(){\r\n");
      out.write("\t\tar = []\r\n");
      out.write("\t\troll()\r\n");
      out.write("\t\trandom_seed.innerHTML += '<option selected>'+ ar +'</option>'\r\n");
      out.write("\t\tarFun(ar)\r\n");
      out.write("\t}\r\n");
      out.write("\t// ================================================================================\t\r\n");
      out.write("\t // 事故: java環境的 js設定 疑似不允許即時更新選框值，故使用重寫方式作設計功能\r\n");
      out.write("\t function roll_col(arc,v){ // ( 被修改 , 欲修改 )\r\n");
      out.write("\t\t arc.innerHTML = ''\r\n");
      out.write("\t\t for(i=1; i<50; i++){\r\n");
      out.write("\t\t    \tif(i<10){\r\n");
      out.write("\t\t\t\t\ti = \"0\"+i // 補0\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t    \tif(v == i){arc.innerHTML += \"<option selected>\"+i+\"</option>\"\r\n");
      out.write("\t\t    \t\t}else{arc.innerHTML += \"<option>\"+i+\"</option>\"}\r\n");
      out.write("\t\t    \t}\r\n");
      out.write("\t }\r\n");
      out.write("\t// 事故: 原先用該值作修改即可，因上述事故使用重寫的方式\r\n");
      out.write("\tfunction arFun(ar){\r\n");
      out.write("\t\troll_col(selectNum1,ar[0])\r\n");
      out.write("\t\troll_col(selectNum2,ar[1])\r\n");
      out.write("\t\troll_col(selectNum3,ar[2])\r\n");
      out.write("\t\troll_col(selectNum4,ar[3])\r\n");
      out.write("\t\troll_col(selectNum5,ar[4])\r\n");
      out.write("\t\troll_col(selectNum6,ar[5])\r\n");
      out.write("\t}\r\n");
      out.write("\t// ================================================================================\r\n");
      out.write("\r\n");
      out.write("\t// 單一選框: 將當前值(下選單) 更新為 開獎號碼\r\n");
      out.write("\tfunction handler_form(fs){\r\n");
      out.write("\t\tlet lst = [] // 空陣列\r\n");
      out.write("\t\tlet arf = fs.options[fs.selectedIndex].innerText // 取得單個(下選單)修改過的值\r\n");
      out.write("\t\tthis.value = arf // fs為該 option欄位(下選單)，將其值替換為 修改過的值\r\n");
      out.write("\r\n");
      out.write("\t\t// 上述修改完成，進行 取得當前值(通用函式)\r\n");
      out.write("\t\tn = currentNum()\r\n");
      out.write("\t\t// 以當前值 n 建立開獎號碼欄位\r\n");
      out.write("\t\trandom_seed.innerHTML += '<option selected>'+ n +'</option>'\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t// 開獎號碼欄位: 紀錄每組號碼並將選取的組合 設定為 當前值(下選單)\r\n");
      out.write("\tfunction handler_option(ar){\r\n");
      out.write("\t\tlet ars = ar.options[ar.selectedIndex].innerText;\r\n");
      out.write("\t\tars = ars.split(',')\r\n");
      out.write("\t\tarFun(ars)\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t// 建構:建立 6組下選單欄位(49個號碼)\r\n");
      out.write("\tfunction constructor(){\r\n");
      out.write("\t\tfor(var i=1; i<=49; i++){\r\n");
      out.write("\t\t\tif(i<10){ // 補0\r\n");
      out.write("\t\t\t\ti = \"0\"+i\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(ar[0] == i){\r\n");
      out.write("\t\t\t\tselectNum1.innerHTML += '<option selected>'+ i +'</option>'\r\n");
      out.write("\t\t\t}else{selectNum1.innerHTML += '<option>'+ i +'</option>'}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(ar[1] == i){\r\n");
      out.write("\t\t\t\tselectNum2.innerHTML += '<option selected>'+ i +'</option>'\r\n");
      out.write("\t\t\t}else{selectNum2.innerHTML += '<option>'+ i +'</option>'}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(ar[2] == i){\r\n");
      out.write("\t\t\t\tselectNum3.innerHTML += '<option selected>'+ i +'</option>'\r\n");
      out.write("\t\t\t}else{selectNum3.innerHTML += '<option>'+ i +'</option>'}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(ar[3] == i){\r\n");
      out.write("\t\t\t\tselectNum4.innerHTML += '<option selected>'+ i +'</option>'\r\n");
      out.write("\t\t\t}else{selectNum4.innerHTML += '<option>'+ i +'</option>'}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(ar[4] == i){\r\n");
      out.write("\t\t\t\tselectNum5.innerHTML += '<option selected>'+ i +'</option>'\r\n");
      out.write("\t\t\t}else{selectNum5.innerHTML += '<option>'+ i +'</option>'}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(ar[5] == i){\r\n");
      out.write("\t\t\t\tselectNum6.innerHTML += '<option selected>'+ i +'</option>'\r\n");
      out.write("\t\t\t}else{selectNum6.innerHTML += '<option>'+ i +'</option>'}\t\t\r\n");
      out.write("\t\t };\r\n");
      out.write("\t}\r\n");
      out.write("\t \r\n");
      out.write("    </script>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");

   String n1 = request.getParameter("n1");
   String n2 = request.getParameter("n2");
   String n3 = request.getParameter("n3");
   String n4 = request.getParameter("n4");
   String n5 = request.getParameter("n5");
   String n6 = request.getParameter("n6");
   
   System.out.println("index.jsp:頁面取得資料：");
   System.out.println(n1+" "+n2+" "+n3+" "+n4+" "+n5+" "+n6);

	

      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
